{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<header>\n",
    "        <div style=\"overflow: auto;\">\n",
    "    </div>\n",
    "    <div style=\"text-align: center;\">\n",
    "        <h1> AMS Data1 - Assignment </h1>\n",
    "        <h4> Week 1.1 &emsp; Water – Paralympics</h4>\n",
    "        <h6>&copy; 2023, Group 10. Layne, Michelle, Yifan</h6>     \n",
    "    </div>\n",
    "    <br>   \n",
    "    <br>\n",
    "</header>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Background:\n",
    "\n",
    "Paris is hosting the Paralympics in 2024. One of the events at the Paralympics is an open water swimming event in the Seine (apparently the water is clean or so the French say). Since the City of Amsterdam thinks it is better than Paris, they want to host an event before the Paralympics, snubbing the Parisians. The idea is to host a 5km. open water swimming event through the canals of Amsterdam. You are asked by the municipality of Amsterdam to advise on the feasibility of the event from the perspective of the safety of the partaking athletes from an environmental perspective. The event is going to be hosted in May. "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Our Solutions:\n",
    "\n",
    "To convey a proper opinion on the feasibility of the event, our group would need data about the quality of the water in the canals and the most populous routes for water transport and canal boats. The water quality data would need to include escherichia coli (EC) and intestinal entercoocci (IE) levels because this would tell us the sewage level at the location. The water transport and canal boat data would tell us where the busiest routes are, so therefore where to most likely avoid. However, the water quality of the canals will be a priority to impacting routes. Oxygen, temperature, and turbidity are also good indicators of water quality, so data sets with this information would be helpful in conveying the feasibility.  \n",
    "\n",
    " \n",
    "\n",
    "The following table is a list of relevant data sets we found and the format they are stored in. In the table we answer the questions about file format, data type, the readability and the required python library.  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<table>\n",
    "<thead>\n",
    "<tr>\n",
    "<th style=\"text-align:left\">Name</th>\n",
    "<th style=\"text-align:left\">Source/Link</th>\n",
    "<th style=\"text-align:left\">File format</th>\n",
    "<th style=\"text-align:left\">Data type</th>\n",
    "<th style=\"text-align:left\">Scale</th>\n",
    "<th style=\"text-align:left\">Python library</th>\n",
    "<th style=\"text-align:left\">Readable or not</th>\n",
    "</tr>\n",
    "</thead>\n",
    "<tbody>\n",
    "<tr>\n",
    "<td style=\"text-align:left\">Measurement results surface water quality research, 2019</td>\n",
    "<td style=\"text-align:left\">https://onderzoek.amsterdam.nl/dataset/water-in-amsterdam</td>\n",
    "<td style=\"text-align:left\">Excel file</td>\n",
    "<td style=\"text-align:left\">Numerical</td>\n",
    "<td style=\"text-align:left\">Municipal scale (Municipality of Amsterdam)</td>\n",
    "<td style=\"text-align:left\">\"pandas\"\" \"openpyxl\" library, use the read_excel() function.</td>\n",
    "<td style=\"text-align:left\">Yes</td>\n",
    "</tr>\n",
    "<tr>\n",
    "<td style=\"text-align:left\">Mapping our water: water visibility</td>\n",
    "<td style=\"text-align:left\">https://www.waternet.nl/ons-water/oppervlaktewater/water-in-kaart/</td>\n",
    "<td style=\"text-align:left\">Online map</td>\n",
    "<td style=\"text-align:left\">Geodata (points, with numerical data)</td>\n",
    "<td style=\"text-align:left\">Municipal scale (Municipality of Amsterdam)</td>\n",
    "<td style=\"text-align:left\">(maybe we can use “requests” library to make HTTP requests and retrieve raw data)</td>\n",
    "<td style=\"text-align:left\">Yes</td>\n",
    "</tr>\n",
    "<tr>\n",
    "<td style=\"text-align:left\">Mapping our water: Salt</td>\n",
    "<td style=\"text-align:left\">https://www.waternet.nl/ons-water/oppervlaktewater/water-in-kaart/</td>\n",
    "<td style=\"text-align:left\">Online map</td>\n",
    "<td style=\"text-align:left\">Geodata (points, with numerical data)</td>\n",
    "<td style=\"text-align:left\">Municipal scale (Municipality of Amsterdam)</td>\n",
    "<td style=\"text-align:left\">(maybe we can use “requests” library to make HTTP requests and retrieve raw data)</td>\n",
    "<td style=\"text-align:left\">Yes</td>\n",
    "</tr>\n",
    "<tr>\n",
    "<td style=\"text-align:left\">Mapping our water: Oxygen</td>\n",
    "<td style=\"text-align:left\">https://www.waternet.nl/ons-water/oppervlaktewater/water-in-kaart/</td>\n",
    "<td style=\"text-align:left\">Online map</td>\n",
    "<td style=\"text-align:left\">Geodata (points, with numerical data)</td>\n",
    "<td style=\"text-align:left\">Municipal scale (Municipality of Amsterdam)</td>\n",
    "<td style=\"text-align:left\">(maybe we can use “requests” library to make HTTP requests and retrieve raw data)</td>\n",
    "<td style=\"text-align:left\">Yes</td>\n",
    "</tr>\n",
    "<tr>\n",
    "<td style=\"text-align:left\">zwemwater.nl</td>\n",
    "<td style=\"text-align:left\">https://www.zwemwater.nl/home</td>\n",
    "<td style=\"text-align:left\">Online map</td>\n",
    "<td style=\"text-align:left\">Geodata (points, with numerical data)</td>\n",
    "<td style=\"text-align:left\">National scale (Netherlands)</td>\n",
    "<td style=\"text-align:left\">(maybe we can use “requests” library to make HTTP requests and retrieve raw data)</td>\n",
    "<td style=\"text-align:left\">Yes</td>\n",
    "</tr>\n",
    "<tr>\n",
    "<td style=\"text-align:left\">Boarding and disembarking points & berths passenger vessels</td>\n",
    "<td style=\"text-align:left\">https://maps.amsterdam.nl/varen/</td>\n",
    "<td style=\"text-align:left\">Online map</td>\n",
    "<td style=\"text-align:left\">Geodata (points with symbolic labels)</td>\n",
    "<td style=\"text-align:left\">Municipal scale (Municipality of Amsterdam)</td>\n",
    "<td style=\"text-align:left\">(maybe we can use “requests” library to make HTTP requests and retrieve raw data)</td>\n",
    "<td style=\"text-align:left\">Yes</td>\n",
    "</tr>\n",
    "</tbody>\n",
    "</table>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "However, we were unable to find more extensive and precise water quality testing data for the Amsterdam canals, and could only extrapolate and speculate based on data from a few monitoring points. Having such data would enable us to make more targeted recommendations."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Read and print by Python\n",
    "\n",
    "The following program is to read and print the data from <i>Measurement results surface water quality research, 2019</i>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['9.4.1   Meetresultaten kwaliteitsonderzoek oppervlaktewater, 2019', None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, 'zuurstof-']\n",
      "[None, None, None, ' totaal fosfor', 'totaal stikstof', 'chloride', 'temperatuur', 'doorzicht', 'zuurgraad', 'verzadiging']\n",
      "[None, None, None, 'zmg 1)', 'zmg', 'zmg', 'max', 'min', 'zmg', 'zmg']\n",
      "['meetpunt', 'Afvoergebied gemalen', 'type', 'mg P/l', 'mg N/l', 'mg Cl/l', 'oC', 'm', 'pH', '%']\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "['BER001', 'W.H. Vliegenbos, KG.7', 'm8', 0.76, 2.3, 1162, 19.7, 0.2, 7.6, 25]\n",
      "['BLM001', 'Bijlmer, gemaal Bijlmer/Provincialeweg', 'm8', 0.35, 3.1, 1767, 19.2, 0.2, 7.9, 73]\n",
      "['BLW005', 'Polder de Nieuwe Bullewijk, gemaal Hoogendijk 2', 'm8', 0.39, 3.7, 1583, 20.4, 0.2, 8.2, 67]\n",
      "['BTV003', 'Binnendijkse Buitenvelderse Polder, gemaal Amsteldijk 271', 'm8', 0.76, 3.5, 111, 23.3, 0.6, 7.6, 63]\n",
      "['DMP001', 'Diemerpolder, gemaal kade langs ark 15', 'm8', 0.6, 1.8, 164, 21, 0.4, 7.9, 71]\n",
      "['DMP020', 'Diemerpolder, gemaal Ajaxpad', 'm8', 1.12, 2.7, 72, 16.4, 0.3, 7.4, 36]\n",
      "['ERP002', 'Erasmuspark-Noord', 'm10', 2.03, 2.6, 198, 20.1, 0.3, 8, 51]\n",
      "['FVP003', 'Flevopark', 'm10', 0.74, 3.4, 217, 20.7, 0.2, 7.6, 44]\n",
      "['GGP020', 'Gaasperplas, gemaal Zuid Bijlmer', 'm20', 0.25, 2.5, 113, 19.8, 0.4, 7.6, 55]\n",
      "['GSW002', 'Gemeenschapspolder-West, gemaal Verlengde Stammerdijk', 'm8', 0.24, 2.2, 132, 21.8, 0.4, 7.6, 64]\n",
      "['IJB001', 'Haveneiland en Rieteiland, gemaal Haveneiland', 'm10', 0.25, 1.5, 86, 21.4, 0.4, 8.1, 73]\n",
      "['MAP004', 'Middelveldse Akerpolder, gemaal Shillingdijk', 'm1', 0.83, 2.2, 119, 19.6, 0.2, 7.7, 51]\n",
      "['MPA001', 'Middelpolder onder Amstelveen, gemaal Amsteldijk-Noord 68', 'm10', 0.49, 3.6, 290, 24, 0.2, 8, 50]\n",
      "['NWS001', 'Gemaal Nieuw-Sloten', 'm8', 0.95, 2.5, 71, 20.7, 0.4, 8.1, 75]\n",
      "['OBL012', 'Osdorperbinnenpolder, Geuzenveld-West,  mpt 2 no-hoek', 'm1', 0.73, 4.5, 152, 20.7, 0.1, 7.5, 29]\n",
      "['OBL021', 'Osdorperbinnenpolder, Maaltocht naast brug', 'm1', 1.53, 3.8, 202, 21.3, 0.3, 7.8, 48]\n",
      "['OBP003', 'Overbraker Binnenpolder, Poldergemaal Haarlemmerweg', 'm1', 0.75, 3.1, 416, 20.4, 0.2, 7.8, 55]\n",
      "['ODP001', 'Gemaal Overdiemerpolder', 'm1', 0.53, 2.3, 158, 21.1, 0.3, 7.7, 40]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "['1) Zomergemiddelde.', None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, 'kwaliteit volgens Kaderrichtlijn Water (KRW) Monitoring Oppervlaktewater', None, None, None, None, None, None, None, None]\n",
      "[None, None, None, 'zeer goed', 'goed', 'matig', 'ontoereikend', 'slecht', None, None]\n",
      "['9.4.1   Meetresultaten kwaliteitsonderzoek oppervlaktewater, 2019 (vervolg)', None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, 'zuurstof-']\n",
      "[None, None, None, ' totaal fosfor', 'totaal stikstof', 'chloride', 'temperatuur', 'doorzicht', 'zuurgraad', 'verzadiging']\n",
      "[None, None, None, 'zmg 1)', 'zmg', 'zmg', 'max', 'min', 'zmg', 'zmg']\n",
      "['meetpunt', 'Afvoergebied gemalen', 'type', 'mg P/l', 'mg N/l', 'mg Cl/l', 'oC', 'm', 'pH', '%']\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "['OSB007', 'Osdorperbovenpolder, Raasdorperweg', 'm8', 1.47, 8.1, 178, 23.8, 0.05, 8.2, 77]\n",
      "['OTP002', 'Oosterpark, brug t.h.v. Tropenmuseum', 'm10', 0.43, 3.4, 182, 23.5, 0.2, 8, 62]\n",
      "['RKP001', 'Riekerpolder, gemaal Jaagpad', 'm8', 0.62, 1.6, 133, 21.1, 0.6, 8, 62]\n",
      "['RKP012', 'Riekerpolder, gemaal Ringvaartdijk', 'm8', 1.01, 3, 143, 20.3, 0.3, 7.6, 39]\n",
      "['SBI001', 'Sloterbinnen- en Middelveldsepolder, gemaal Akersloot', 'm8', 0.54, 2, 158, 21.4, 0.5, 7.9, 55]\n",
      "['SBI027', 'Sloterbinnen- en Middelveldsepolder, gemaal Gerbrandypark', 'm20', 1.65, 3.3, 123, 21.4, 0.4, 7.6, 28]\n",
      "['SBI031', 'Sloterbinnen- en Middelveldsepolder, gemaal Delflandlaan', 'm20', 0.73, 2.1, 137, 22.1, 0.6, 7.8, 38]\n",
      "['SPP005', 'Gemaal Sarphatipark', 'm1', 0.4, 3.2, 173, 24.2, 0.3, 8, 69]\n",
      "['TDO001', 'Noorder IJpolder, gemaal Tuindorp Oostzaan', 'm8', 1.51, 3.3, 488, 20.5, 0.5, 8, 42]\n",
      "['VGD001', 'Venserpolder, gemaal Groot Duivendrechtse Polder', 'm8', 0.45, 2.3, 93, 18.9, 0.6, 7.6, 43]\n",
      "['VGD009', 'Venserpolder, gemaal Duivendrechtsekade', 'm8', 0.11, 2.3, 213, 19.8, 0.6, 7.8, 71]\n",
      "['VGD021', 'Venserpolder (volkstuinparken), gemaal Tuinpark Dijkzicht', 'm8', 0.76, 4.3, 183, 21.6, 0.3, 7.6, 33]\n",
      "['VGD027', 'Duivendrechtsepolder, zuidelijke aanvoer naar gemaal', 'm8', 0.41, 3.6, 513, 20.4, 0.2, 8.1, 73]\n",
      "['VGD029', 'Venserpolder, gemaal Volkstuinen Amstelglorie', 'm8', 0.5, 3.7, 482, 18.8, 0.3, 7.7, 55]\n",
      "['VGD032', 'Gemaal polder De Toekomst', 'm8', 0.56, 4, 325, 18.8, 0.2, 7.8, 51]\n",
      "['VOP009', 'Gemaal Vondelpark', 'm8', 1.06, 1.8, 273, 20.6, 0.5, 8.3, 58]\n",
      "['WGM002', 'Watergraafsmeer, gemaal Oosterringdijk', 'm8', 0.33, 3.4, 188, 18.2, 0.1, 8.3, 69]\n",
      "['WGM006', 'Watergraafsmeer, gemaal Von Liebigweg', 'm8', 0.32, 3.2, 287, 17.6, 0.3, 7.8, 31]\n",
      "['WGM007', 'Watergraafsmeer, gemaal Radioweg', 'm8', 0.19, 3.3, 169, 16.4, 0.2, 7.7, 36]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "['1) Zomergemiddelde.', None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, 'kwaliteit volgens Kaderrichtlijn Water (KRW) Monitoring Oppervlaktewater', None, None, None, None, None, None, None, None]\n",
      "[None, None, None, 'zeer goed', 'goed', 'matig', 'ontoereikend', 'slecht', None, None]\n",
      "['9.4.1   Meetresultaten kwaliteitsonderzoek oppervlaktewater, 2019 (slot)', None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, 'zuurstof-']\n",
      "[None, None, None, ' totaal fosfor', 'totaal stikstof', 'chloride', 'temperatuur', 'doorzicht', 'zuurgraad', 'verzadiging']\n",
      "[None, None, None, 'zmg 1)', 'zmg', 'zmg', 'max', 'min', 'zmg', 'zmg']\n",
      "['meetpunt', None, 'type', 'mg P/l', 'mg N/l', 'mg Cl/l', 'oC', 'm', 'pH', '%']\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, 'inlaten', None, None, None, None, None, None, None, None]\n",
      "['ADM060', 'Inlaat Riekerhaven/gemeentewerf', 'm6b', 0.21, 2.9, 420, 22.4, 0.8, 7.8, 65]\n",
      "['AMS007', 'Amstel brug Rijksweg A9', 'm6b', 0.25, 3.5, 707, 24.3, 0.4, 8, 60]\n",
      "['SBI019', 'Inlaat Sloterplas', 'm10', 0.53, 1.9, 157, 21.5, 0.8, 8, 60]\n",
      "['SBI020', 'Sloterbinnenpolder, inlaat sportcomplex', 'm10', 0.98, 2.4, 157, 23.2, 0.4, 7.8, 57]\n",
      "['SBI028', 'Baden Powelweg', 'm20', 1.05, 3.4, 117, 21.2, 0.4, 7.6, 31]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, 'boezem', None, None, None, None, None, None, None, None]\n",
      "['ADM076', 'Brug over Keizersgracht bij Leidsegracht', 'm6b', 0.23, 3.1, 597, 24.1, 0.3, 7.8, 57]\n",
      "['AMS033', 'Amstel t.o. nr. 319/ten zuiden A10', 'm6b', 0.29, 3.8, 633, 26, 0.4, 8, 67]\n",
      "['BUL002', 'Brug over  Bullewijk bij Machineweg Ouderkerk a/d Amstel', 'm6b', 0.26, 3.6, 847, 21.2, 0.2, 8.1, 76]\n",
      "['DED002', 'Fietsbrug over Diem', 'm6b', 0.13, 2.1, 133, 21.5, 0.5, 8, 76]\n",
      "['GAA005', 'Gaasp t.h.v. Stammerdijk 38 ', 'm6b', 0.1, 2.2, 142, 23.5, 0.6, 8.1, 91]\n",
      "['HLV004', 'Trekvaart Halfweg-Amsterdam', 'm10', 0.83, 1.7, 418, 21.6, 0.4, 7.7, 42]\n",
      "['KVV002', 'Brug over Kostverlorenvaart bij de CLercqstraat', 'm6b', 0.31, 2.4, 678, 21.5, 0.6, 7.9, 48]\n",
      "['WTV004', 'Brug over Weespertrekvaart bij Rozenburglaan', 'm6b', 0.12, 2.2, 192, 19.5, 0.8, 7.8, 72]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, 'plassen', None, None, None, None, None, None, None, None]\n",
      "['GGP050', 'Gaasperplas middenop', 'm20', 0.02, 1.2, 200, 26.4, 1.5, 8.5, 89]\n",
      "['HBP050', 'Ouderkerkerplas middenop', 'm20', 0.03, 1.4, 692, 24.1, 2.5, 8.6, 90]\n",
      "['NIJ003', 'Noorder-IJplas middenop', 'm30', 0.03, 1.1, 729, 21.9, 0.7, 8.6, 91]\n",
      "['SBI010', 'Sloterplas middenop', 'm20', 0.45, 1.4, 155, 22.9, 1.6, 8.6, 97]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "['1) Zomergemiddelde.', None, None, None, None, None, None, None, None, 'bron: Waternet']\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, 'kwaliteit volgens Kaderrichtlijn Water (KRW) Monitoring Oppervlaktewater', None, None, None, None, None, None, None, None]\n",
      "[None, None, None, 'zeer goed', 'goed', 'matig', 'ontoereikend', 'slecht', None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n",
      "[None, None, None, None, None, None, None, None, None, None]\n"
     ]
    }
   ],
   "source": [
    "#pip install pandas\n",
    "#pip install openpyxl\n",
    "\n",
    "#import pandas as pd\n",
    "import openpyxl\n",
    "\n",
    "workbook = openpyxl.load_workbook('Meetresultaten kwaliteitsonderzoek oppervlaktewater.xlsx')\n",
    "sheet = workbook.active\n",
    "\n",
    "for row in sheet.iter_rows(values_only=True):\n",
    "    list_row = list(row)\n",
    "    print(list_row)\n",
    "    #print(list_row[3])\n",
    "\n",
    "\n",
    "#df = pd.read_excel('Meetresultaten kwaliteitsonderzoek oppervlaktewater.xlsx')\n",
    "#print(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
